language: php

os: windows

php:
    - 5.5.9
    - 7.0.7
    - 7.1.0

before_script:
    # Set config files
    - cp phpunit.xml.dist phpunit.xml

notifications:
    email:
        - rechad.sanehy.test@gmail.com