<?php

namespace AppBundle\Repository;

/**
 * CompanySecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanySecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
