<?php

namespace AppBundle\Repository;

/**
 * EnjeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnjeuxRepository extends \Doctrine\ORM\EntityRepository
{
}
