<?php

namespace AppBundle\Repository;

/**
 * ExigenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExigenceRepository extends \Doctrine\ORM\EntityRepository
{
}
