<?php

namespace AppBundle\Repository;

/**
 * PartiePrenanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartiePrenanteRepository extends \Doctrine\ORM\EntityRepository
{
}
