<?php

namespace AppBundle\Repository;

/**
 * RoleProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
