<?php

namespace AppBundle\Repository;

/**
 * RoleUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleUserRepository extends \Doctrine\ORM\EntityRepository
{
}
