<?php

namespace AppBundle\Repository;

/**
 * ValeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValeurRepository extends \Doctrine\ORM\EntityRepository
{
}
