iris_company_homepage:
    path:     /
    defaults: { _controller: IrisCompanyBundle:Default:index }

company:
    path:     /entreprises/add
    defaults: { _controller: IrisCompanyBundle:Company:Add }

iris_company_fiche:
    path:     /entreprises/{id}
    defaults: { _controller: IrisCompanyBundle:Company:Show }

iris_company_liste_fiche:
    path:     /entreprises
    defaults: { _controller: IrisCompanyBundle:Company:ShowAll }