#iris_company_homepage:
#    path:     /
#    defaults: { _controller: IrisCompanyBundle:Default:index }

company:
    path:     /entreprises/add
    method:  [ post ]
    defaults: { _controller: IrisCompanyBundle:Company:Add }

iris_company_edit:
    path:     /entreprises/edit/{id}
    method:  [ put ]
    defaults: { _controller: IrisCompanyBundle:Company:edit }
    requirements:
        page: \d+

iris_company_fiche:
    path:     /entreprises/{id}
    method:  [ get ]
    defaults: { _controller: IrisCompanyBundle:Company:Show }

iris_company_liste_fiche:
    path:     /entreprises
    method:  [ get ]
    defaults: { _controller: IrisCompanyBundle:Company:ShowAll }

iris_company_adduser:
    path:     /entreprises/adduser/{id}
    method:  [ post ]
    defaults: { _controller: IrisCompanyBundle:Company:RegisterUser }
