iris_user:
    resource: "@IrisUserBundle/Resources/config/routing.yml"
    prefix:   /

iris_company:
    resource: "@IrisCompanyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
