#iris_project_homepage:
#    path:     /
#    defaults: { _controller: IrisProjectBundle:Default:index }

project:
    path:     /projets/add
    methods:  [ get, post ]
    defaults: { _controller: IrisProjectBundle:Project:Add }

iris_project_edit:
    path:     /projets/edit/{id}
    methods:  [ get, post ]
    defaults: { _controller: IrisProjectBundle:Project:edit }
    requirements:
        page: \d+

iris_project_fiche:
    path:     /projets/{id}
    methods:  [ get ]
    defaults: { _controller: IrisProjectBundle:Project:Show }

iris_project_liste_fiche:
    path:     /projets
    methods:  [ get ]
    defaults: { _controller: IrisProjectBundle:Project:ShowAll }

iris_project_enjeux_liste:
    path:     /projets/{id}/enjeux
    methods:  [ get ]
    defaults: { _controller: IrisProjectBundle:Enjeux:ShowAll }

iris_project_enjeux_add:
    path:     /projets/{id}/enjeux/add
    methods:  [ get, post ]
    defaults: { _controller: IrisProjectBundle:Enjeux:Add }

iris_project_enjeux_fiche:
    path:     /projets/{idproject}/enjeux/{id}
    methods:  [ get ]
    defaults: { _controller: IrisProjectBundle:Enjeux:Show }

iris_project_enjeux_edit:
    path:     /projets/{idproject}/enjeux/{id}/edit
    methods:  [ get, post ]
    defaults: { _controller: IrisProjectBundle:Enjeux:edit }
    requirements:
        page: \d+