iris_user_homepage:
    path:     /user
    defaults: { _controller: IrisUserBundle:Default:index }
    
iris_liste_user:
    path:     /utilisateurs
    defaults: { _controller: IrisUserBundle:User:ShowAll }

iris_user:
    path:     /utilisateur/{id}
    defaults: { _controller: IrisUserBundle:Profile:Show }
    requirements:
        id: \d+
    


