iris_user_homepage:
    path:     /
    defaults: { _controller: IrisUserBundle:Default:index }
    
iris_liste_user:
    path:     /utilisateurs
    defaults: { _controller: IrisUserBundle:User:ShowAll }

