iris_user_homepage:
    path:     /user
    method:  [ get ]
    defaults: { _controller: IrisUserBundle:Default:index }
    
iris_liste_user:
    path:     /utilisateurs
    method:  [ get ]
    defaults: { _controller: IrisUserBundle:User:ShowAll }

iris_user:
    path:     /utilisateur/{id}
    method:  [ get ]
    defaults: { _controller: IrisUserBundle:Profile:Show }
    


