iris_user_homepage:
    path:     /
    defaults: { _controller: IrisUserBundle:Default:index }

user:
    path:     /user
    defaults: { _controller: IrisUserBundle:User:Add }
    
iris_liste_user:
    path:     /utilisateurs
    defaults: { _controller: IrisUserBundle:User:ShowAll }

